//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleLogsProvider.Logging.MostLogsServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MostLogsServices.ILogSourceService")]
    public interface ILogSourceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogSourceService/ClearMessagesList", ReplyAction="http://tempuri.org/ILogSourceService/ClearMessagesListResponse")]
        void ClearMessagesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogSourceService/StartListening", ReplyAction="http://tempuri.org/ILogSourceService/StartListeningResponse")]
        void StartListening();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogSourceService/StopListening", ReplyAction="http://tempuri.org/ILogSourceService/StopListeningResponse")]
        void StopListening();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogSourceService/GetIsListening", ReplyAction="http://tempuri.org/ILogSourceService/GetIsListeningResponse")]
        bool GetIsListening();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogSourceService/GetLinesStartingWithIndex", ReplyAction="http://tempuri.org/ILogSourceService/GetLinesStartingWithIndexResponse")]
        Awad.Eticket.ModuleLogsProvider.Types.LogMessageInfo[] GetLinesStartingWithIndex(int index);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogSourceServiceChannel : ModuleLogsProvider.Logging.MostLogsServices.ILogSourceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogSourceServiceClient : System.ServiceModel.ClientBase<ModuleLogsProvider.Logging.MostLogsServices.ILogSourceService>, ModuleLogsProvider.Logging.MostLogsServices.ILogSourceService {
        
        public LogSourceServiceClient() {
        }
        
        public LogSourceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogSourceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogSourceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogSourceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ClearMessagesList() {
            base.Channel.ClearMessagesList();
        }
        
        public void StartListening() {
            base.Channel.StartListening();
        }
        
        public void StopListening() {
            base.Channel.StopListening();
        }
        
        public bool GetIsListening() {
            return base.Channel.GetIsListening();
        }
        
        public Awad.Eticket.ModuleLogsProvider.Types.LogMessageInfo[] GetLinesStartingWithIndex(int index) {
            return base.Channel.GetLinesStartingWithIndex(index);
        }
    }
}
